INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (1, 'ЕНГЕЛЬГАРД АРЦНАЙМІТТЕЛЬ ГМБХ',  'Німеччина');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (2, 'БІОНОРИКА СЕ',  'Німеччина');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (3, 'ТЕРНОФАРМ ТОВ', 'Україна');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (4, 'КИЇВМЕДПРЕПАРАТ ПАТ', 'Україна');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (5, 'ГНЦЛС ТОВ ЗДОРОВ`Я', 'Україна');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (6, 'ТОВ ДКП ФАРМАЦЕВТИЧНА ФАБРИКА', 'Україна');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (7, 'ДАРНИЦЯ ПРАТ ФАРМ. ФІРМА', 'Україна');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (8, 'ЧЕРВОНА ЗІРКА ПАТ ХІМЗАВОД', 'Україна');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (9, 'МЕНАРІНІ МАНУФАКТУРІНГ ЛОГІСТІКС ЕНД СЕРВІСЕС С.Р.Л.', 'Італія');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (10, 'ТОВ ФАРМ КОМПАНІЯ ЗДОРОВ`Я', 'Україна');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (11, 'КРАСОТА ТА ЗДОРОВ`Я ТОВ', 'Україна');
INSERT INTO pharmacy.manufacturer (id, name, country) VALUES (12, 'БІОКОН МЕДИЧНЕ НВО ТОВ', 'Україна');